system:
  variables:
    ENV_RELATIONSHIPS: "PLATFORM_RELATIONSHIPS"
    ENV_ROUTES: "PLATFORM_ROUTES"
    ENV_VARIABLES: "PLATFORM_VARIABLES"
    ENV_APPLICATION: "PLATFORM_APPLICATION"
    ENV_ENVIRONMENT: "PLATFORM_ENVIRONMENT"
stage:
  global:
    UPDATE_URLS: true
    SCD_MAX_EXECUTION_TIME: 3600
    SCD_STRATEGY: "quick"
    SCD_THREADS: 3
    SCD_MATRIX:
      "Magento/backend":
        language:
          - en_US
      "Magento/blank": [ ]
      "Magento/luma":
        language:
          - en_US
  build:
    SKIP_SCD: false
  deploy:
    SKIP_SCD: true
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        log_level: '1'
        bot_first_lifetime: '30'
        bot_lifetime: '3600'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 100
